#!/bin/sh

# 给定的脚本名称
script_name="/Users/wukongguoqu/Documents/GitHub/scriptdemo/${1}/${1}.sh"

# 确保脚本存在
if [ ! -f "${script_name}" ]; then
    echo "脚本 ${script_name} 不存在"
    exit 1
fi

# 使脚本可执行
cp ${script_name} ${1}.sh
chmod +x ${1}.sh

# 创建归档文件
# 注意：这里假设只有 ${script_name} 需要被打包
./makeself.sh . "/Users/wukongguoqu/Documents/GitHub/scriptdemo/${1}.run" "${1} script" "./${1}.sh"
./makeself.sh --nox11 ./xxx ./out/xxx_x86.run "OneClick install" ./install.sh
https://github.com/megastep/makeself/releases/download/release-2.5.0/makeself-2.5.0.run
