#!/bin/sh

chmod -R 0775 /etc/init.d /usr/share
touch /etc/crontabs/root

source /etc/openwrt_release
if [[ ! "${DISTRIB_ARCH}" == "x86_64" ]]; then
	sed -i "s?x86_64?${DISTRIB_TARGET}?g" /etc/banner
fi
if [[ "${DISTRIB_ID}" == "ImmortalWrt" ]]; then
	sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
fi

# if [[ -f "/usr/lib/lua/luci/controller/ttyd.lua" ]]; then
# 	sed -i 's?services?system?g' "/usr/lib/lua/luci/controller/ttyd.lua"
# fi

# 如果文件 "/etc/opkg/distfeeds.conf" 中包含 "danshui"
if [[ `grep -c "danshui" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	# 删除包含 "danshui" 的行
	sed -i '/danshui/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "helloworld" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/helloworld/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "passwall" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/passwall/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "OpenClash" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/OpenClash/d' /etc/opkg/distfeeds.conf
fi
if [[ `grep -c "openwrt_x" /etc/opkg/distfeeds.conf` -ge '1' ]]; then
	sed -i '/openwrt_x/d' /etc/opkg/distfeeds.conf
fi

# 如果文件 "/etc/config/dhcp" 中包含 "dns_redirect"
if [[ `grep -c "dns_redirect" /etc/config/dhcp` -ge '1' ]]; then
	# 停止 dnsmasq 服务
	service dnsmasq stop
	# 从文件 "/etc/config/dhcp" 中删除包含 "dns_redirect" 的行
	sed -i '/dns_redirect/d' /etc/config/dhcp
	# 提交配置更改
	uci commit dhcp
	# 启动 dnsmasq 服务
	service dnsmasq start
else
	# 停止 dnsmasq 服务
	service dnsmasq stop
	# 设置 dhcp.@dnsmasq[0].dns_redirect 为 '0'
	uci set dhcp.@dnsmasq[0].dns_redirect='0'
	# 提交配置更改
	uci commit dhcp
	# 启动 dnsmasq 服务
	service dnsmasq start
fi

# 如果文件 "/usr/share/ucode/luci/version.uc" 存在
if [[ -f "/usr/share/ucode/luci/version.uc" ]]; then
	# 删除文件中的 "export const revision" 行
	sed -i '/export const revision/d' "/usr/share/ucode/luci/version.uc"
	# 添加新的 "export const revision" 行
	echo "export const revision = '112233', branch = '';" >> "/usr/share/ucode/luci/version.uc"
fi

if [[ -f "/etc/networkdetection" ]] && [[ `grep -c "networkdetection" /etc/crontabs/root` -eq '0' ]]; then
	rm -rf /etc/networkdetection
fi

luci_web=/usr/lib/lua/luci/view/admin_status/index.htm
if [[ -f '/etc/index.htm' ]]; then
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "/etc/index.htm"
else
	sed -i 's#localtime  = .*#localtime  = os.date("%Y-%m-%d") .. " " .. os.date("%X") .. " " .. translate(os.date("%A")),#g' "${luci_web}"
fi
if [[ -f '/etc/index.htm' ]] && [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "/etc/index.htm"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "/etc/index.htm"
elif [[ `grep -c "(<%=pcdata(ver.luciversion)%>)" "${luci_web}"` -eq '1' ]]; then
	sed -i 's?(<%=pcdata(ver.luciversion)%>)?- <%=pcdata(ver.luciversion)%>?g' "${luci_web}"
fi

sed -i 's?=== WARNING! =====================================?=================== WARNING! ====================?g' /etc/profile

lmo_file="$({ find "/usr/lib/lua/luci/i18n" |grep "zh_Hans.lmo"; } 2>"/dev/null")"
for b in ${lmo_file}
do
	lmo_new_file="$(echo -e "$b"|sed "s/zh_Hans/zh-cn/g")"
	[[ -f "$b" ]] && mv "$b" "${lmo_new_file}" 2>"/dev/null"
done

if [[ -n "$(grep "downloads.openwrt.org" /etc/opkg/distfeeds.conf)" ]]; then
	sed -i 's?downloads.openwrt.org?mirrors.cloud.tencent.com/openwrt?g' /etc/opkg/distfeeds.conf
fi

